-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 16:25:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vendas_sucos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vendas_sucos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendas_sucos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vendas_sucos` ;

-- -----------------------------------------------------
-- Table `vendas_sucos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`clientes` (
  `CPF` VARCHAR(11) NOT NULL,
  `NOME` VARCHAR(100) NULL DEFAULT NULL,
  `ENDERECO` VARCHAR(150) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(50) NULL DEFAULT NULL,
  `CIDADE` VARCHAR(50) NULL DEFAULT NULL,
  `ESTADO` VARCHAR(50) NULL DEFAULT NULL,
  `CEP` VARCHAR(8) NULL DEFAULT NULL,
  `DATA_NASCIMENTO` DATE NULL DEFAULT NULL,
  `IDADE` INT NULL DEFAULT NULL,
  `SEXO` VARCHAR(1) NULL DEFAULT NULL,
  `LIMIDE_CREDITO` FLOAT NULL DEFAULT NULL,
  `VOLUME_COMPRA` FLOAT NULL DEFAULT NULL,
  `PRIMEIRA_COMPRA` TINYINT(1) NULL DEFAULT NULL,
  `notas_numero` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`CPF`, `notas_numero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`produtos` (
  `CODIGO` VARCHAR(10) NOT NULL,
  `DESCRITOR` VARCHAR(100) NULL DEFAULT NULL,
  `SABOR` VARCHAR(50) NULL DEFAULT NULL,
  `TAMANHO` VARCHAR(50) NULL DEFAULT NULL,
  `EMBALAGEM` VARCHAR(50) NULL DEFAULT NULL,
  `PRECO_LISTA` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`vendedores` (
  `MATRICULA` VARCHAR(5) NOT NULL,
  `NOME` VARCHAR(100) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(50) NULL DEFAULT NULL,
  `COMISSAO` FLOAT NULL DEFAULT NULL,
  `DATA_ADMISSAO` DATE NULL DEFAULT NULL,
  `FERIAS` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`MATRICULA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`notas` (
  `numero` VARCHAR(5) NOT NULL,
  `data_venda` DATE NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `matricula` VARCHAR(5) NOT NULL,
  `imposto` FLOAT NULL DEFAULT NULL,
  `clientes_CPF` VARCHAR(11) NOT NULL,
  `vendedores_MATRICULA` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `FK_CLIENTES_idx` (`cpf` ASC) VISIBLE,
  INDEX `fk_notas_clientes1_idx` (`clientes_CPF` ASC) VISIBLE,
  INDEX `fk_notas_vendedores1_idx` (`vendedores_MATRICULA` ASC) VISIBLE,
  CONSTRAINT `fk_notas_clientes1`
    FOREIGN KEY (`clientes_CPF`)
    REFERENCES `vendas_sucos`.`clientes` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_vendedores1`
    FOREIGN KEY (`vendedores_MATRICULA`)
    REFERENCES `vendas_sucos`.`vendedores` (`MATRICULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`itens_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`itens_notas` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `QUANTIDADE` INT NULL DEFAULT NULL,
  `PRECO` FLOAT NULL DEFAULT NULL,
  `produtos_CODIGO` VARCHAR(10) NOT NULL,
  `notas_numero` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`NUMERO`, `produtos_CODIGO`, `notas_numero`),
  INDEX `fk_itens_notas_produtos1_idx` (`produtos_CODIGO` ASC) VISIBLE,
  INDEX `fk_itens_notas_notas1_idx` (`notas_numero` ASC) VISIBLE,
  CONSTRAINT `fk_itens_notas_produtos1`
    FOREIGN KEY (`produtos_CODIGO`)
    REFERENCES `vendas_sucos`.`produtos` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_notas_notas1`
    FOREIGN KEY (`notas_numero`)
    REFERENCES `vendas_sucos`.`notas` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
