 CREATE TABLE TB_Clientes
 (CPF VARCHAR(11),
 NOME VARCHAR(100),
 ENDERECO VARCHAR(150),
 ENDERECO2 VARCHAR(150),
 BAIRRO VARCHAR(50),
 CIDADE VARCHAR(50),
 ESTADO VARCHAR(10),
 CEP VARCHAR(8),
 IDADE SMALLINT,
 SEXO VARCHAR(1),
 LIMITE_CREDITO FLOAT,
 VOLUME_COMPRA FLOAT,
 PRIMEIRA_COMPRA BIT(1));
 
 